### ISSUE TITLE
Installing Giraffe on the full .NET framework

### ISSUE THREAD

**Issue by nojaf** [dustinmoris/Giraffe#46] opened 2017-04-27 08:17 UTC
I'm not entirely sure this is a problem with Giraffe but I'm unable to install Giraffe on a full framework project using .NET 4.6.1. Which according to [this table](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries) also should support Net standard 1.6.

```
Install-Package : Could not install package 'Giraffe 0.1.0-alpha015'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembl
y references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  Giraffe -Pre 
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
It is also unclear to me what the **with tooling 2.0** bit is in the table.

**Comment by dustinmoris** [comment] 2017-04-27 08:20
Hi, yeah that is a strange one. Did you try to add it via NuGet in VS 2017? Based on the table I would expect that with VS 2017 and via the default add nuget package dialog it should work, assuming that the "default" Microsoft way with their latest tools would work. If that is true, then you can work backwards to figure out what the problem is in your case.

**Comment by nojaf** [comment] 2017-04-27 08:23
Yes using VS 2017 with the dialog and Package Manager Console. No luck.

**Comment by nojaf** [comment] 2017-04-27 08:33
I'm able to install all the dependencies of Giraffe so something is missing in Giraffe itself.
I did notice the the [csproj of MvcCore](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc/Microsoft.AspNetCore.Mvc.csproj#L7) mentions `net46` where [Giraffe](https://github.com/dustinmoris/Giraffe/blob/develop/src/Giraffe/Giraffe.fsproj#L10) doesn't.

Could that be the missing link?

**Comment by dustinmoris** [comment] 2017-04-27 08:35
Hmmm yes I think this could be it. Do you want to quickly try it out locally and if it works I can quickly add it and publish a new package.

**Comment by nojaf** [comment] 2017-04-27 08:36
Ok, I'll give it a shot.

**Comment by dustinmoris** [comment] 2017-05-04 10:06
Released with the latest version. Thanks!

**Closed by dustinmoris** 2017-05-04 10:06 UTC

**Comment by nojaf** [comment] 2017-05-04 10:53
Thanks for the release, I can confirm that the `0.1.0-alpha016` package works with net461.
